#docker-compose.yml for local development
version: '3.8'
services:
  app:
    build: .
    container_name: pincheck_app
    restart: always
    expose:
      - "5000"
    volumes:
      - ./app:/app
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION}