name: Deploy to EC2

on:
	push:
		branches:
			- main

jobs:
	deploy:
		runs-on: ubuntu-latest

		steps:
			- name: Checkout code
				uses: actions/checkout@v3

			- name: Copy project files to EC2
				uses: appleboy/scp-action@v0.1.4
				with:
					host: ${{ secrets.EC2_HOST }}
					username: ${{ secrets.EC2_USER }}
					key: ${{ secrets.EC2_SSH_KEY }}
					source: "."
					target: "~/pincheck"

			- name: SSH into EC2 and deploy
				uses: appleboy/ssh-action@v0.1.6
				with:
					host: ${{ secrets.EC2_HOST }}
					username: ${{ secrets.EC2_USER }}
					key: ${{ secrets.EC2_SSH_KEY }}
					script: |
						cd ~/pincheck
						echo "Setting AWS credentials..."
						mkdir -p ~/.aws
						echo "[default]" > ~/.aws/credentials
						echo "aws_access_key_id=${{ secrets.AWS_ACCESS_KEY_ID }}" >> ~/.aws/credentials
						echo "aws_secret_access_key=${{ secrets.AWS_SECRET_ACCESS_KEY }}" >> ~/.aws/credentials
						echo "[default]" > ~/.aws/config
						echo "region=${{ secrets.AWS_REGION }}" >> ~/.aws/config
						docker-compose -f docker-compose.prod.yml down
						docker-compose -f docker-compose.prod.yml up --build -d
